<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-17 at 10:54:48.
 */
class AdjacencyMatrixTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AdjacencyMatrix
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AdjacencyMatrix;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AdjacencyMatrix::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AdjacencyMatrix::addEdge
     * @todo   Implement testAddEdge().
     */
    public function testAddEdge() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AdjacencyMatrix::getMatrixAsArray
     * @todo   Implement testGetMatrixAsArray().
     */
    public function testGetMatrixAsArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AdjacencyMatrix::getMatrix
     * @todo   Implement testGetMatrix().
     */
    public function testGetMatrix() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
